import test from 'node:test';import assert from 'node:assert/strict';import {INITIAL_LANES} from '../dist-test/src/fixtures.js';import {authoritativeSnapshot,decideAction,getAttentionItems,prepareActionSafe,recommendNextMove,requestHumanGate,simulateExternalLaneUpdate} from '../dist-test/src/domain.js';
const base=()=>({lanes:structuredClone(INITIAL_LANES),proposedAction:null,receipt:null,failureReceipt:null});
test('recommendation binds the selected lane revision and state',()=>{const r=recommendNextMove(INITIAL_LANES);assert.equal(getAttentionItems(INITIAL_LANES)[0].id,'proof-repair');assert.equal(r.lane_id,'proof-repair');assert.equal(r.observed_revision,1);assert.equal(r.observed_state,'NEEDS_REVIEW')});
test('normal prepare succeeds only from the bound current revision',()=>{const s=base();const r=recommendNextMove(s.lanes);const p=prepareActionSafe(s,r.lane_id,r.observed_revision,r.observed_state);assert.equal(p.outcome.status,'PREPARED');assert.equal(p.state.proposedAction?.status,'PROPOSED');assert.equal(p.state.proposedAction?.source_lane_revision,1)});
test('stale recommendation fails closed without authoritative action-state mutation',()=>{const s=base();const r=recommendNextMove(s.lanes);const changed=simulateExternalLaneUpdate(s,r.lane_id);const before=authoritativeSnapshot(changed);const p=prepareActionSafe(changed,r.lane_id,r.observed_revision,r.observed_state);assert.equal(p.outcome.status,'BLOCKED_SAFE');assert.equal(p.outcome.failure_receipt?.failure_code,'STALE_STATE');assert.equal(p.outcome.failure_receipt?.expected_lane_revision,1);assert.equal(p.outcome.failure_receipt?.observed_lane_revision,2);assert.equal(p.outcome.failure_receipt?.action_state_changed,false);assert.equal(authoritativeSnapshot(p.state),before)});
test('fresh read and re-recommend recovers after stale-state stop',()=>{let s=base();const old=recommendNextMove(s.lanes);s=simulateExternalLaneUpdate(s,old.lane_id);const blocked=prepareActionSafe(s,old.lane_id,old.observed_revision,old.observed_state);const fresh=recommendNextMove(blocked.state.lanes);assert.equal(fresh.observed_revision,2);const recovered=prepareActionSafe(blocked.state,fresh.lane_id,fresh.observed_revision,fresh.observed_state);assert.equal(recovered.outcome.status,'PREPARED');assert.equal(recovered.state.proposedAction?.source_lane_revision,2)});
test('occupied Human Gate returns typed stop and preserves the guarded proposal',()=>{let s=base();const r=recommendNextMove(s.lanes);s=prepareActionSafe(s,r.lane_id,r.observed_revision,r.observed_state).state;s=requestHumanGate(s);const before=authoritativeSnapshot(s);const other=s.lanes.find(x=>x.id==='event-radar');const blocked=prepareActionSafe(s,'event-radar',other.revision,other.state);assert.equal(blocked.outcome.failure_receipt?.failure_code,'HUMAN_GATE_OCCUPIED');assert.equal(blocked.outcome.failure_receipt?.preserved_action?.lane_id,'proof-repair');assert.equal(blocked.outcome.failure_receipt?.action_state_changed,false);assert.equal(authoritativeSnapshot(blocked.state),before)});
test('invalid or unknown prepare input is diagnostic-only',()=>{const s=base();const before=authoritativeSnapshot(s);const invalid=prepareActionSafe(s,undefined,undefined);assert.equal(invalid.outcome.failure_receipt?.failure_code,'INVALID_INPUT');assert.equal(authoritativeSnapshot(invalid.state),before);const unknown=prepareActionSafe(s,'missing-lane',1);assert.equal(unknown.outcome.failure_receipt?.failure_code,'UNKNOWN_LANE');assert.equal(authoritativeSnapshot(unknown.state),before)});
test('Human approve and reject remain UI-owned decisions',()=>{let s=base();const r=recommendNextMove(s.lanes);s=requestHumanGate(prepareActionSafe(s,r.lane_id,r.observed_revision,r.observed_state).state);assert.equal(decideAction(s,'APPROVED','2026-09-29T00:00:00Z').receipt?.result,'PASS');assert.equal(decideAction(s,'REJECTED','2026-09-29T00:00:00Z').receipt?.result,'NO_ACTION')});
