import test from 'node:test';import assert from 'node:assert/strict';import {INITIAL_LANES} from '../dist-test/src/fixtures.js';import {authoritativeSnapshot,simulateExternalLaneUpdate} from '../dist-test/src/domain.js';import {registerDiamondControlTools,WEBMCP_TOOL_NAMES} from '../dist-test/src/webmcp.js';
async function harness(){let state={lanes:structuredClone(INITIAL_LANES),proposedAction:null,receipt:null,failureReceipt:null};const tools=[];const r=await registerDiamondControlTools(()=>state,n=>{state=n},{registerTool:t=>{tools.push(t)}});return{get state(){return state},set state(v){state=v},tools,status:r.status}}
const tool=(h,name)=>h.tools.find(t=>t.name===name);
test('registers exactly five tools',async()=>{const h=await harness();assert.equal(h.status,'AVAILABLE');assert.deepEqual(h.tools.map(t=>t.name),[...WEBMCP_TOOL_NAMES])});
test('read-only tools do not mutate workspace',async()=>{const h=await harness();const before=JSON.stringify(h.state);await tool(h,'get_workspace_state').execute({});await tool(h,'get_attention_items').execute({});await tool(h,'recommend_next_move').execute({});assert.equal(JSON.stringify(h.state),before)});
test('WebMCP normal path carries revision into reversible proposal',async()=>{const h=await harness();const r=await tool(h,'recommend_next_move').execute({});const p=await tool(h,'prepare_action').execute({lane_id:r.lane_id,expected_revision:r.observed_revision,expected_state:r.observed_state});assert.equal(p.status,'PREPARED');assert.equal(h.state.proposedAction?.source_lane_revision,r.observed_revision);const g=await tool(h,'request_human_gate').execute({});assert.equal(g.gate_state,'AWAITING_HUMAN');assert.equal(h.state.proposedAction?.status,'AWAITING_HUMAN')});
test('WebMCP stale-state path stops safely and recovers after fresh recommendation',async()=>{const h=await harness();const old=await tool(h,'recommend_next_move').execute({});h.state=simulateExternalLaneUpdate(h.state,old.lane_id);const before=authoritativeSnapshot(h.state);const blocked=await tool(h,'prepare_action').execute({lane_id:old.lane_id,expected_revision:old.observed_revision,expected_state:old.observed_state});assert.equal(blocked.status,'BLOCKED_SAFE');assert.equal(blocked.failure_receipt.failure_code,'STALE_STATE');assert.equal(blocked.failure_receipt.action_state_changed,false);assert.equal(authoritativeSnapshot(h.state),before);const fresh=await tool(h,'recommend_next_move').execute({});const recovered=await tool(h,'prepare_action').execute({lane_id:fresh.lane_id,expected_revision:fresh.observed_revision,expected_state:fresh.observed_state});assert.equal(recovered.status,'PREPARED')});
test('WebMCP cannot replace an action already awaiting Human review',async()=>{const h=await harness();const r=await tool(h,'recommend_next_move').execute({});await tool(h,'prepare_action').execute({lane_id:r.lane_id,expected_revision:r.observed_revision,expected_state:r.observed_state});await tool(h,'request_human_gate').execute({});const other=h.state.lanes.find(x=>x.id==='event-radar');const before=authoritativeSnapshot(h.state);const blocked=await tool(h,'prepare_action').execute({lane_id:'event-radar',expected_revision:other.revision,expected_state:other.state});assert.equal(blocked.status,'BLOCKED_SAFE');assert.equal(blocked.failure_receipt.failure_code,'HUMAN_GATE_OCCUPIED');assert.equal(blocked.failure_receipt.preserved_action.lane_id,'proof-repair');assert.equal(authoritativeSnapshot(h.state),before)});
test('malformed direct tool call returns BLOCKED_SAFE instead of mutating',async()=>{const h=await harness();const before=authoritativeSnapshot(h.state);const blocked=await tool(h,'prepare_action').execute({lane_id:'proof-repair'});assert.equal(blocked.status,'BLOCKED_SAFE');assert.equal(blocked.failure_receipt.failure_code,'INVALID_INPUT');assert.equal(authoritativeSnapshot(h.state),before)});
