import type { WorkspaceState } from './types.js'
import {getAttentionItems,prepareAction,recommendNextMove,requestHumanGate} from './domain.js'
type Tool={name:string;title?:string;description:string;inputSchema:Record<string,unknown>;annotations?:Record<string,unknown>;execute:(input:any)=>Promise<unknown>|unknown}
type ModelContext={registerTool:(tool:Tool,options?:unknown)=>Promise<void>|void}
declare global{interface Document{modelContext?:ModelContext}}
export const WEBMCP_TOOL_NAMES=['get_workspace_state','get_attention_items','recommend_next_move','prepare_action','request_human_gate'] as const
export async function registerDiamondControlTools(getState:()=>WorkspaceState,setState:(state:WorkspaceState)=>void,modelContext?:ModelContext){const mc=modelContext??(typeof document!=='undefined'?document.modelContext:undefined);if(!mc)return{status:'UNAVAILABLE' as const,registered:[] as string[]};const tools:Tool[]=[
{name:'get_workspace_state',title:'Get workspace state',description:'Read normalized work lanes, proposed action, Human Gate state, and proof receipt. Never mutates state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>({workspace:getState()})},
{name:'get_attention_items',title:'Get attention items',description:'Read work lanes that need attention and why. Never mutates state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>({items:getAttentionItems(getState().lanes)})},
{name:'recommend_next_move',title:'Recommend next move',description:'Recommend one bounded next move. Advisory only; grants no execution authority.',inputSchema:{type:'object',properties:{lane_ids:{type:'array',items:{type:'string'}}},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:{lane_ids?:string[]})=>recommendNextMove(getState().lanes,input?.lane_ids)},
{name:'prepare_action',title:'Prepare action',description:'Prepare a reversible PROPOSED action. Cannot approve, publish, commit, send, or bypass Human Gate.',inputSchema:{type:'object',properties:{lane_id:{type:'string'}},required:['lane_id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{lane_id:string})=>{if(!input?.lane_id)throw new Error('lane_id is required');const next=prepareAction(getState(),input.lane_id);setState(next);return{proposed_action:next.proposedAction}}},
{name:'request_human_gate',title:'Request Human Gate',description:'Move current proposed action into explicit Human review. Cannot approve or reject on behalf of the Human.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async()=>{const next=requestHumanGate(getState());setState(next);return{gate_state:'AWAITING_HUMAN',required_decision:'Human must choose Approve or Reject in the visible UI.',proposed_action:next.proposedAction}}}
];for(const tool of tools)await mc.registerTool(tool);return{status:'AVAILABLE' as const,registered:tools.map(t=>t.name)}}
